import type { Metadata } from "next";
import { IBM_Plex_Sans } from "next/font/google";
import "./globals.css";

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
	// Start of Selection
};

const ibm_plex_sans = IBM_Plex_Sans({
	subsets: ["latin"],
	display: "swap",
	variable: "--font-ibm_plex_sans",
	weight: ["100", "200", "300", "400", "500", "600", "700"],
});

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body className={ibm_plex_sans.variable}>{children}</body>
		</html>
	);
}
